AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  GitHubFullRepositoryName:
    Type: String
    Default: ruzickap/k8s-tf-eks-argocd

Resources:
  User:
    Type: AWS::IAM::User
    Properties:
      UserName: aws-cli
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  Role:
    Type: AWS::IAM::Role
    Properties:
      Description: "Role for running Terrafrom code for GH Actions and local user"
      RoleName: GitHubOidcFederatedRole
      MaxSessionDuration: 36000
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                # Allows only actions in this repository to assume the role
                token.actions.githubusercontent.com:sub:
                  - !Sub "repo:${GitHubFullRepositoryName}:*"
            Effect: Allow
            Principal:
              Federated: !Ref GitHubOidc
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                - !GetAtt User.Arn
  GitHubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - "6938fd4d98bab03faadb97b34396831e3780aea1"
      Url: https://token.actions.githubusercontent.com

Outputs:
  RoleArn:
    Value: !GetAtt Role.Arn
  UserArn:
    Value: !GetAtt User.Arn
  GitHubOidcArn:
    Value: !GetAtt GitHubOidc.Arn
